/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./components/ui/accordion/AccordionTrigger.vue')['default']
    Alert: typeof import('./components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./components/ui/alert/AlertTitle.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    Drawer: typeof import('./components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./components/ui/drawer/DrawerTitle.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./components/ui/scroll-area/ScrollBar.vue')['default']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs/TabsTrigger.vue')['default']
    Textarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
